# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-sitemap, jekyll-seo-tag]

# Site URL (GitHub Pages)
url:                 'https://qiqi-lu.github.io'
baseurl:             ''

# Customise site metadata (used by the Jekyll SEO tag)
title:              'Qiqi Lu'
description:        'Southern Medical University'
author:             'Qiqi Lu'
timezone:           'Asia/Shanghai'
