# Navigation menu
menu:
- {name: 'About', path: 'menu', url: 'about'}
- {name: 'Publications', path: 'menu', url: 'publications'}
- {name: 'Patents', path: 'menu', url: 'patents'}
- {name: 'Awards', path: 'menu', url: 'awards'}
- {name: 'News', path: 'menu', url: 'news'}
- {name: 'Contact', path: 'menu', url: 'contact'}

# Available social icons are powered by Font Awesome + Academicons,
# so you can use any icon that they offer.
# google-scholar and orcid use Academicons (ai ai-*); others use Font Awesome (fa fa-*).
social:
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=aXP6u2IAAAAJ&hl=en'}
- {icon: 'orcid',          link: 'https://orcid.org/0000-0001-6066-0690'}
- {icon: 'github',         link: 'https://github.com/qiqi-lu'}
- {icon: 'envelope',       link: 'mailto:136303971@qq.com'}
- {icon: 'linkedin',       link: 'https://www.linkedin.com/in/qiqi-lu/'}
